NIFTY50 = [
"RELIANCE.NS","HDFCBANK.NS","ICICIBANK.NS","INFY.NS","TCS.NS",
"ITC.NS","LT.NS","SBIN.NS","AXISBANK.NS","KOTAKBANK.NS",
"ASIANPAINT.NS","MARUTI.NS","TITAN.NS","BAJFINANCE.NS",
"HCLTECH.NS","SUNPHARMA.NS","NTPC.NS","BHARTIARTL.NS"
]

NIFTY_SYMBOL = "^NSEI"